### ISSUE TITLE
tealium updated unity plugin it is still using the 4.1 plugin which doesn't work

### ISSUE THREAD

**Issue by subhamC** [Tealium/unity-plugin#10]
when will the tealium updated unity plugin come out it is still using the 4.1 plugin which doesn't work for android all the events get queued. Doesn't go to the server

**Comment by jameskeith** [comment]
hi @subhamC 
The latest branch should now support v5 of the Tealium iOS and Android SDKs - please let us know if you still have any problems.
regards
James
